---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-with-skaffold
  labels:
    app: ci-with-skaffold
spec:
  selector:
    matchLabels:
      app: ci-with-skaffold
  replicas: 1
  template:
    metadata:
      labels:
        app: ci-with-skaffold
    spec:
      containers:
      - name: ci-with-skaffold
        image: account_number.dkr.ecr.ap-northeast-1.amazonaws.com/ci-with-skaffold
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: ""
          - name: DB_PORT
            value: ""
          - name: DB_USER
            value: ""
          - name: DB_PASS
            value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: ci-with-skaffold
  labels:
    app: ci-with-skaffold
spec:
  type: NodePort
  selector:
    app: ci-with-skaffold
  ports:
  - name: 8080-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
