apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop-with-skaffold
spec:
  template:
    spec:
      containers:
      - name: develop-with-skaffold
        imagePullPolicy: Never
        env:
          - name: DB_HOST
            value: host.docker.internal
          - name: DB_PORT
            value: 15432
          - name: DB_USER
            value: postgres
          - name: DB_PASS
            value: mysecretpassword
